steps:
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
        if [ -d "iac/environments/$_PROJECT" ]; then
          cd iac/environments/$_PROJECT
          terraform init -backend-config=config/${_ENV}.conf;
        else
          for dir in iac/environments/*/
          do
            cd ${dir}
            env=${dir%*/}
            env=${env#*/}
            echo ""
            echo "*************** TERRAFOM INIT ******************"
            echo "******* At environment: ${env} ********"
            echo "*************************************************"
            terraform init || exit 1
            cd ../../
          done
        fi   